### ISSUE TITLE
Breaks on nodejs 0.12, os.homedir() does not exist

### ISSUE THREAD

**Issue by jonnor** [Daplie/node-ddns-client#6]
After hacking this to be hardcoded, rest of app seems 0.12 compatible.

If you do not want to support node 0.12, please add something like `{ "engines" : { "node" : ">=4.0.0" } }` to package.json

**Comment by coolaj86** [comment]
Ah, yes. I suppose I could use the homedir package instead...

**Comment by coolaj86** [comment]
try now

**Comment by jonnor** [comment]
Confirmed working. Thanks for the superquick fix!
